app = 'bot-llamadas-creativemb'
primary_region = 'gru'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '3008'
 
[[mounts]]
  source = 'bot_data'
  destination = '/data'

[http_service]
  internal_port = 3008
  force_https = true
  auto_stop_machines = false # Cambiado para que el bot no se apague solo
  auto_start_machines = true
  min_machines_running = 1    # Cambiado a 1 para que siempre esté activo
  processes = ['app']

  [[http_service.checks]]
    grace_period = "60s"      
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/v1/status"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1