name: Control Horario Bot
on:
  schedule:
    # 🟢 RUTINA DE ENCENDIDO (Alrededor de 5:00 AM Colombia)
    - cron: '58 9 * * *'   # Intento 1: 4:58 AM (Minuto "raro" para evitar la fila de GitHub)
    - cron: '10 10 * * *'  # Intento 2: 5:10 AM (Respaldo por si falló el primero)

    # 🔴 RUTINA DE APAGADO (Alrededor de 10:00 PM Colombia)
    - cron: '2 3 * * *'    # Intento 1: 10:02 PM (Minuto "raro" sin fila de espera)
    - cron: '15 3 * * *'   # Intento 2: 10:15 PM (Respaldo por si falló el primero)
    
  workflow_dispatch:      # Botón Manual
    inputs:
      accion_manual:
        description: '¿Qué deseas hacer con el bot?'
        required: true
        default: 'encender'
        type: choice
        options:
          - encender
          - apagar

jobs:
  gestion_maquinas:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: Ejecutar Cambio de Escala
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          ACCION=""
          CRON_USADO="${{ github.event.schedule }}"

          if [ "${{ github.event_name }}" = "schedule" ]; then
            
            # Si se activó con las alarmas de la mañana
            if [ "$CRON_USADO" = "58 9 * * *" ] || [ "$CRON_USADO" = "10 10 * * *" ]; then
              ACCION="encender"
              echo "⏰ Horario de mañana detectado. Acción: ENCENDER."
            
            # Si se activó con las alarmas de la noche
            elif [ "$CRON_USADO" = "2 3 * * *" ] || [ "$CRON_USADO" = "15 3 * * *" ]; then
              ACCION="apagar"
              echo "💤 Horario de noche detectado. Acción: APAGAR."
            fi

          else
            # Si alguien presionó el botón manual en GitHub
            ACCION="${{ github.event.inputs.accion_manual }}"
            echo "👤 Botón manual usado. Acción: $ACCION"
          fi

          # Ejecutar en Fly.io según la acción
          if [ "$ACCION" = "encender" ]; then
            echo "🚀 Encendiendo el bot sin borrar datos..."
            flyctl machine start $(flyctl machine list -a bot-llamadas-creativemb -q)
            
          elif [ "$ACCION" = "apagar" ]; then
            echo "🛑 Apagando el bot de forma segura..."
            flyctl machine stop $(flyctl machine list -a bot-llamadas-creativemb -q)
            
          else
            echo "⚠️ Hubo un error reconociendo la alarma."
          fi