name: Control Horario Bot
on:
  schedule:
    - cron: '0 10 * * *'  # 5:00 AM Colombia (Se despierta)
    - cron: '0 3 * * *'   # 10:00 PM Colombia (Se apaga)
  workflow_dispatch:      # Para que puedas prenderlo manualmente si quieres

jobs:
  gestion_maquinas:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: Ejecutar Cambio de Escala
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          # Calculamos la hora de Colombia restando 5 horas al sistema
          HORA=$(date -u -d "-5 hours" +%H)
          echo "La hora en Colombia es las $HORA:00"

          # Si la hora es igual o mayor a las 5 AM Y menor a las 10 PM (22:00)
          if [ "$HORA" -ge "05" ] && [ "$HORA" -lt "22" ]; then
            echo "Horario laboral detectado. Encendiendo bot..."
            flyctl scale count 1 --app bot-llamadas-creativemb --yes
          else
            echo "Horario de descanso detectado. Apagando bot..."
            flyctl scale count 0 --app bot-llamadas-creativemb --yes
          fi